# Generated by Django 4.2.7 on 2023-11-26 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('term', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(max_length=255)),
                ('program', models.CharField(default='Undergraduate', max_length=255)),
                ('faculty', models.CharField(blank=True, max_length=255, null=True)),
                ('descriptions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('Day', 'Day'), ('Evening', 'Evening')], default='Day', max_length=255)),
                ('exam', models.CharField(choices=[('Midterm', 'Midterm'), ('Final', 'Final')], default='Midterm', max_length=255)),
                ('semester', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], default='Spring', max_length=255)),
                ('year', models.IntegerField(default=2023)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('about', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('department', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='DiuQuestionBankAPI.departments')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('qid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('approval', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Approved', max_length=255)),
                ('filePath', models.TextField()),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='DiuQuestionBankAPI.courses')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semesters', to='DiuQuestionBankAPI.semester')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_questions', to='DiuQuestionBankAPI.users')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='DiuQuestionBankAPI.departments'),
        ),
    ]
