# Generated by Django 4.2.7 on 2023-11-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiuQuestionBankAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='exam',
            field=models.CharField(choices=[('Midterm', 'Midterm'), ('Final', 'Final')], default='Midterm', max_length=255),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], default='Spring', max_length=255),
        ),
        migrations.AlterField(
            model_name='semester',
            name='shift',
            field=models.CharField(choices=[('Day', 'Day'), ('Evening', 'Evening')], default='Day', max_length=255),
        ),
    ]
