# Generated by Django 4.2.7 on 2023-11-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiuQuestionBankAPI', '0002_alter_semester_exam_alter_semester_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='faculty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
