# Generated by Django 4.2.7 on 2023-11-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiuQuestionBankAPI', '0003_alter_departments_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='rejected',
        ),
        migrations.AlterField(
            model_name='questions',
            name='approved',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Spring', max_length=255),
        ),
    ]
