# Generated by Django 4.2.7 on 2023-11-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiuQuestionBankAPI', '0004_remove_questions_rejected_alter_questions_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='approved',
        ),
        migrations.AddField(
            model_name='questions',
            name='approval',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Approved', max_length=255),
        ),
    ]
