# Generated by Django 4.2.7 on 2023-11-23 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DiuQuestionBankAPI', '0005_remove_questions_approved_questions_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='DiuQuestionBankAPI.courses'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semesters', to='DiuQuestionBankAPI.semester'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_questions', to='DiuQuestionBankAPI.users'),
        ),
    ]
